---
openapi: 3.0.0
info:
  title: greenshouse minitoring system
  description: API for the greenhouse monitoring system
  version: 1.0.0
servers:
- url: /
paths:
  /stats:
    get:
      tags:
        - devices
      summary: gets the event stats
      operationId: app.get_stats
      description: Gets temperature reading stats
      responses:
        '200':
          description: Successfully returned a list of temperature readings
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ReadingStats'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    ReadingStats:
      required:
      - num_temp_readings
      - max_temp_reading
      - max_humidity_reading
      - max_mositure_reading
      
      type: object
      properties:
        num_temp_readings:
          type: integer
          example: 900
        max_temp_reading:
          type: integer
          example: 100
        max_humidity_reading:
          type: integer
          example: 1000
        max_mositure_reading:
          type: integer
          example: 5000
        
    
    
  