---
openapi: 3.0.0
info:
  title: greenshouse minitoring system
  description: API for the greenhouse monitoring system
  version: 1.0.0
servers:
- url: /

paths:
  /readings/temperature:
    
    post:
      tags:
      - devices
      summary: reports temperature readings
      description: Adds a new temperature reading to the system
      operationId: app.report_temperature_reading
      requestBody:
        description: Reading item to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TemperatureReadings'
      responses:
        "201":
          description: item created
        "400":
          description: invalid input, object invalid
  /readings/co2readings:
    post:
      tags:
      - devices
      summary: reports co2 readings
      description: Adds a new co2 reading to the system
      operationId: app.report_co2_reading
      requestBody:
        description: Reading item to ad
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/co2readings'
      responses:
        "201":
          description: item created
        "400":
          description: invalid input, object invalid
components:
  schemas:
    TemperatureReadings:
      required:
      - date_time
      - greenhouse_id
      - humidity
      - soil_moisture
      - temperature_reading
      type: object
      properties:
        greenhouse_id:
          type: string
          format: uuid
        temperature_reading:
          type: integer
          example: 45
        humidity:
          type: integer
          example: 30
        soil_moisture:
          type: integer
          example: 40
        date_time:
          type: string
          format: date-time
    co2readings:
      required:
      - co2_readings
      - date_time
      - greenhouse_id
      - humidity
      - soil_moisture
      type: object
      properties:
        greenhouse_id:
          type: string
          format: uuid
        co2_readings:
          type: integer
          example: 45
        humidity:
          type: integer
          example: 30
        soil_moisture:
          type: integer
          example: 40
        date_time:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
